services:
  gatesentry:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatesentry
    restart: unless-stopped

    network_mode: host

    volumes:
      - ./docker_root:/usr/local/gatesentry/gatesentry

    environment:
      - TZ=Asia/Singapore
