// Comprehensive list of common MIME types for autocomplete suggestions.
// Users are NOT limited to these values — free-text entry is allowed.

export const MIME_TYPES: string[] = [
    // Application
    "application/atom+xml",
    "application/ecmascript",
    "application/epub+zip",
    "application/gzip",
    "application/java-archive",
    "application/javascript",
    "application/json",
    "application/ld+json",
    "application/manifest+json",
    "application/msword",
    "application/octet-stream",
    "application/ogg",
    "application/pdf",
    "application/pkcs7-mime",
    "application/pkcs7-signature",
    "application/pkcs8",
    "application/pkcs10",
    "application/postscript",
    "application/rdf+xml",
    "application/rss+xml",
    "application/rtf",
    "application/sql",
    "application/typescript",
    "application/vnd.api+json",
    "application/vnd.apple.installer+xml",
    "application/vnd.apple.mpegurl",
    "application/vnd.google-earth.kml+xml",
    "application/vnd.google-earth.kmz",
    "application/vnd.mozilla.xul+xml",
    "application/vnd.ms-excel",
    "application/vnd.ms-excel.sheet.macroEnabled.12",
    "application/vnd.ms-fontobject",
    "application/vnd.ms-powerpoint",
    "application/vnd.ms-project",
    "application/vnd.ms-works",
    "application/vnd.oasis.opendocument.chart",
    "application/vnd.oasis.opendocument.database",
    "application/vnd.oasis.opendocument.formula",
    "application/vnd.oasis.opendocument.graphics",
    "application/vnd.oasis.opendocument.presentation",
    "application/vnd.oasis.opendocument.spreadsheet",
    "application/vnd.oasis.opendocument.text",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.rar",
    "application/vnd.visio",
    "application/wasm",
    "application/x-7z-compressed",
    "application/x-abiword",
    "application/x-bzip",
    "application/x-bzip2",
    "application/x-cdf",
    "application/x-csh",
    "application/x-debian-package",
    "application/x-freearc",
    "application/x-httpd-php",
    "application/x-latex",
    "application/x-msdownload",
    "application/x-perl",
    "application/x-python-code",
    "application/x-redhat-package-manager",
    "application/x-sh",
    "application/x-shockwave-flash",
    "application/x-tar",
    "application/x-tex",
    "application/x-www-form-urlencoded",
    "application/x-x509-ca-cert",
    "application/xhtml+xml",
    "application/xml",
    "application/xslt+xml",
    "application/zip",

    // Audio
    "audio/3gpp",
    "audio/3gpp2",
    "audio/aac",
    "audio/ac3",
    "audio/aiff",
    "audio/amr",
    "audio/basic",
    "audio/flac",
    "audio/midi",
    "audio/mp3",
    "audio/mp4",
    "audio/mpeg",
    "audio/ogg",
    "audio/opus",
    "audio/vorbis",
    "audio/wav",
    "audio/webm",
    "audio/x-aac",
    "audio/x-aiff",
    "audio/x-flac",
    "audio/x-m4a",
    "audio/x-matroska",
    "audio/x-ms-wma",
    "audio/x-ms-wax",
    "audio/x-pn-realaudio",
    "audio/x-wav",

    // Font
    "font/collection",
    "font/otf",
    "font/sfnt",
    "font/ttf",
    "font/woff",
    "font/woff2",

    // Image
    "image/apng",
    "image/avif",
    "image/bmp",
    "image/gif",
    "image/heic",
    "image/heif",
    "image/ico",
    "image/jpeg",
    "image/jxl",
    "image/png",
    "image/svg+xml",
    "image/tiff",
    "image/vnd.microsoft.icon",
    "image/webp",
    "image/x-icon",
    "image/x-ms-bmp",
    "image/x-png",
    "image/x-tga",

    // Message
    "message/rfc822",

    // Model
    "model/gltf+json",
    "model/gltf-binary",
    "model/obj",
    "model/stl",

    // Multipart
    "multipart/form-data",
    "multipart/mixed",
    "multipart/related",

    // Text
    "text/cache-manifest",
    "text/calendar",
    "text/css",
    "text/csv",
    "text/html",
    "text/javascript",
    "text/markdown",
    "text/plain",
    "text/richtext",
    "text/tab-separated-values",
    "text/vcard",
    "text/vtt",
    "text/x-component",
    "text/x-handlebars-template",
    "text/x-java-source",
    "text/x-python",
    "text/x-script.python",
    "text/xml",
    "text/yaml",

    // Video
    "video/3gpp",
    "video/3gpp2",
    "video/avi",
    "video/h264",
    "video/h265",
    "video/mp2t",
    "video/mp4",
    "video/mpeg",
    "video/ogg",
    "video/quicktime",
    "video/webm",
    "video/x-flv",
    "video/x-m4v",
    "video/x-matroska",
    "video/x-ms-asf",
    "video/x-ms-wmv",
    "video/x-msvideo",
];

// Pre-built ComboBox items array for Carbon ComboBox component
export const MIME_TYPE_ITEMS = MIME_TYPES.map((type) => ({
    id: type,
    text: type,
}));
