// Code generated by go-bindata. (@generated) DO NOT EDIT.

// Package main generated by go-bindata.
// sources:
// filterfiles/blockedmimes.json
// filterfiles/blockedsites.json
// filterfiles/dontbump.json
// filterfiles/exceptionsitelist.json
// filterfiles/stopwords.json
package gatesentry2filters

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _filterfilesBlockedmimesJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\x56\xca\x4e\xad\x2c\xcf\x2f\x4a\x29\x56\xb2\x8a\x8e\xad\x05\x04\x00\x00\xff\xff\xdb\x0b\x7f\x11\x0f\x00\x00\x00")

func filterfilesBlockedmimesJsonBytes() ([]byte, error) {
	return bindataRead(
		_filterfilesBlockedmimesJson,
		"filterfiles/blockedmimes.json",
	)
}

func filterfilesBlockedmimesJson() (*asset, error) {
	bytes, err := filterfilesBlockedmimesJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "filterfiles/blockedmimes.json", size: 15, mode: os.FileMode(493), modTime: time.Unix(1696621979, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _filterfilesBlockedsitesJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\x56\xca\x4e\xad\x2c\xcf\x2f\x4a\x29\x56\xb2\x8a\xe6\x52\x50\xa8\xe6\x52\x50\x50\x50\x50\x72\xce\xcf\x2b\x49\xcd\x2b\x51\xb2\x52\x50\x2a\xce\x4b\x2c\x48\x4c\x29\xd6\x4b\xce\xcf\x55\xd2\x81\xc8\x06\x27\xe7\x17\xa5\x2a\x59\x29\x18\x70\x29\x28\xd4\x72\xc5\xd6\x02\x02\x00\x00\xff\xff\xfe\x13\x9f\x9d\x45\x00\x00\x00")

func filterfilesBlockedsitesJsonBytes() ([]byte, error) {
	return bindataRead(
		_filterfilesBlockedsitesJson,
		"filterfiles/blockedsites.json",
	)
}

func filterfilesBlockedsitesJson() (*asset, error) {
	bytes, err := filterfilesBlockedsitesJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "filterfiles/blockedsites.json", size: 69, mode: os.FileMode(493), modTime: time.Unix(1697003956, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _filterfilesDontbumpJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\x56\xca\x4e\xad\x2c\xcf\x2f\x4a\x29\x56\xb2\x8a\xe6\x52\x50\xa8\xe6\x52\x50\x50\x50\x50\x72\xce\xcf\x2b\x49\xcd\x2b\x51\xb2\x52\x50\x4a\xcf\x2c\xc9\x28\x4d\xd2\x4b\xce\xcf\x55\xd2\x81\x48\x06\x27\xe7\x17\xa5\x2a\x59\x29\x18\x72\x29\x28\xd4\x72\xc5\xd6\x02\x02\x00\x00\xff\xff\xc0\x7c\x8d\x9f\x44\x00\x00\x00")

func filterfilesDontbumpJsonBytes() ([]byte, error) {
	return bindataRead(
		_filterfilesDontbumpJson,
		"filterfiles/dontbump.json",
	)
}

func filterfilesDontbumpJson() (*asset, error) {
	bytes, err := filterfilesDontbumpJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "filterfiles/dontbump.json", size: 68, mode: os.FileMode(493), modTime: time.Unix(1697003972, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _filterfilesExceptionsitelistJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\x56\xca\x4e\xad\x2c\xcf\x2f\x4a\x29\x56\xb2\x8a\xe6\x52\x50\xe0\x8a\xad\x05\x04\x00\x00\xff\xff\xeb\x7c\x5f\x43\x13\x00\x00\x00")

func filterfilesExceptionsitelistJsonBytes() ([]byte, error) {
	return bindataRead(
		_filterfilesExceptionsitelistJson,
		"filterfiles/exceptionsitelist.json",
	)
}

func filterfilesExceptionsitelistJson() (*asset, error) {
	bytes, err := filterfilesExceptionsitelistJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "filterfiles/exceptionsitelist.json", size: 19, mode: os.FileMode(493), modTime: time.Unix(1697003981, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _filterfilesStopwordsJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\x56\xca\x4e\xad\x2c\xcf\x2f\x4a\x29\x56\xb2\x8a\x8e\xad\x05\x04\x00\x00\xff\xff\xdb\x0b\x7f\x11\x0f\x00\x00\x00")

func filterfilesStopwordsJsonBytes() ([]byte, error) {
	return bindataRead(
		_filterfilesStopwordsJson,
		"filterfiles/stopwords.json",
	)
}

func filterfilesStopwordsJson() (*asset, error) {
	bytes, err := filterfilesStopwordsJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "filterfiles/stopwords.json", size: 15, mode: os.FileMode(493), modTime: time.Unix(1696866082, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"filterfiles/blockedmimes.json":      filterfilesBlockedmimesJson,
	"filterfiles/blockedsites.json":      filterfilesBlockedsitesJson,
	"filterfiles/dontbump.json":          filterfilesDontbumpJson,
	"filterfiles/exceptionsitelist.json": filterfilesExceptionsitelistJson,
	"filterfiles/stopwords.json":         filterfilesStopwordsJson,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("nonexistent") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"filterfiles": &bintree{nil, map[string]*bintree{
		"blockedmimes.json":      &bintree{filterfilesBlockedmimesJson, map[string]*bintree{}},
		"blockedsites.json":      &bintree{filterfilesBlockedsitesJson, map[string]*bintree{}},
		"dontbump.json":          &bintree{filterfilesDontbumpJson, map[string]*bintree{}},
		"exceptionsitelist.json": &bintree{filterfilesExceptionsitelistJson, map[string]*bintree{}},
		"stopwords.json":         &bintree{filterfilesStopwordsJson, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
